name: Update Digital Peak code repo

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Push
      uses: Digital-Peak/gitlab-mirror-and-ci-action@master
      with:
        args: "https://code.digital-peak.com/Digital-Peak/DPAttachments"
      env:
        FOLLOW_TAGS: true
        FORCE_PUSH: true
        GITLAB_HOSTNAME: "code.digital-peak.com"
        GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: 4
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
